---
- name: Add Datadog repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 382E94DE # Pulled from https://docs.datadoghq.com/agent/basic_agent_usage/ubuntu/
    state: present
  tags:
    - datadog

- name: Add Datadog repository
  apt_repository:
    repo: 'deb https://apt.datadoghq.com/ stable 6'
    state: present
    update_cache: yes
  tags:
    - datadog

- name: Install Datadog
  apt:
    name: datadog-agent
    state: present
    update_cache: yes
    cache_valid_time: 300
  tags:
    - datadog
  when: install_datadog

- name: Configure datadog
  template:
    src: datadog.cfg.j2
    dest: /etc/datadog-agent/datadog.yaml
    mode: 0644
  tags:
    - datadog
  notify:
    - restart datadog

- name: Start service
  service:
    name: datadog-agent
    enabled: yes
    state: started
