language: node_js
node_js:
  - '12'
cache: yarn
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - yarn run build
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
          - npx semantic-release
