git clone https://github.com/mdn/kuma.git
git clone https://github.com/mdn/kumascript.git
git clone https://github.com/mdn/wp-promote-mdn.git
git clone https://github.com/mdn/mdn-app-template.git
git clone https://github.com/mdn/to-do-notifications.git
git clone https://github.com/mdn/battery-quickstart-starter-template.git
git clone https://github.com/mdn/battery-quickstart-finished-example.git
git clone https://github.com/mdn/addon-sdk-content-scripts.git
git clone https://github.com/mdn/web-dictaphone.git
git clone https://github.com/mdn/voice-change-o-matic.git
git clone https://github.com/mdn/violent-theremin.git
git clone https://github.com/mdn/e10s-example-addons.git
git clone https://github.com/mdn/sw-test.git
git clone https://github.com/mdn/browsercompat.git
git clone https://github.com/mdn/voice-change-o-matic-float-data.git
git clone https://github.com/mdn/repl-panel.git
git clone https://github.com/mdn/audio-channels-demo.git
git clone https://github.com/mdn/beginner-html-site.git
git clone https://github.com/mdn/beginner-html-site-styled.git
git clone https://github.com/mdn/beginner-html-site-scripted.git
git clone https://github.com/mdn/browsercompat-data.git
git clone https://github.com/mdn/simple-web-worker.git
git clone https://github.com/mdn/simple-shared-worker.git
git clone https://github.com/mdn/sphinx-theme.git
git clone https://github.com/mdn/canvas-raycaster.git
git clone https://github.com/mdn/beginning-programming-content-kit.git
git clone https://github.com/mdn/world-clock.git
git clone https://github.com/mdn/fetch-examples.git
git clone https://github.com/mdn/content-kit-template.git
git clone https://github.com/mdn/webalyzer.git
git clone https://github.com/mdn/samples-server.git
git clone https://github.com/mdn/viewsourceconf.git
git clone https://github.com/mdn/webvr-tests.git
git clone https://github.com/mdn/performance-scenarios.git
git clone https://github.com/mdn/advanced-js-fundamentals-ck.git
git clone https://github.com/mdn/webextensions-examples.git
git clone https://github.com/mdn/webgl-examples.git
git clone https://github.com/mdn/browser-api-demo.git
git clone https://github.com/mdn/web-speech-api.git
git clone https://github.com/mdn/browsercompat-cm.git
git clone https://github.com/mdn/learning-area.git
git clone https://github.com/mdn/browser-compat-data.git
git clone https://github.com/mdn/devtools-examples.git
git clone https://github.com/mdn/whitestorm-demo.git
git clone https://github.com/mdn/data.git
git clone https://github.com/mdn/django-locallibrary-tutorial.git
git clone https://github.com/mdn/django-diy-blog.git
git clone https://github.com/mdn/crossbrowser-testing-lab.git
git clone https://github.com/mdn/express-locallibrary-tutorial.git
git clone https://github.com/mdn/helm-charts.git
git clone https://github.com/mdn/css-examples.git
git clone https://github.com/mdn/js-examples.git
git clone https://github.com/mdn/archived_kumascript.git
git clone https://github.com/mdn/webaudio-examples.git
git clone https://github.com/mdn/s3-config.git
git clone https://github.com/mdn/indexeddb-examples.git
git clone https://github.com/mdn/dom-examples.git
git clone https://github.com/mdn/mdn.git
git clone https://github.com/mdn/webassembly-examples.git
git clone https://github.com/mdn/web-tech-games.git
git clone https://github.com/mdn/interactive-examples.git
git clone https://github.com/mdn/doc-linter-webextension.git
git clone https://github.com/mdn/doc-linter-rules.git
git clone https://github.com/mdn/html-examples.git
git clone https://github.com/mdn/headless-examples.git
git clone https://github.com/mdn/learning-area-de.git
git clone https://github.com/mdn/learning-area-pt-br.git
git clone https://github.com/mdn/web-components-examples.git
git clone https://github.com/mdn/pab.git
git clone https://github.com/mdn/pwa-examples.git
git clone https://github.com/mdn/mdn-fiori.git
git clone https://github.com/mdn/bob.git
git clone https://github.com/mdn/browser-compat-toolkit.git
git clone https://github.com/mdn/fibonacci-worker.git
git clone https://github.com/mdn/sprints.git
git clone https://github.com/mdn/infra.git
git clone https://github.com/mdn/ansible-jenkins.git
git clone https://github.com/mdn/imsc.git
git clone https://github.com/mdn/short-descriptions.git
git clone https://github.com/mdn/stumptown-content.git
git clone https://github.com/mdn/mdn.dev.git
git clone https://github.com/mdn/houdini-examples.git
git clone https://github.com/mdn/perf-examples.git
git clone https://github.com/mdn/developer-portal.git
git clone https://github.com/mdn/yari.git
git clone https://github.com/mdn/insights.git
git clone https://github.com/mdn/mdn-minimalist.git
git clone https://github.com/mdn/mdn-dinocons.git
git clone https://github.com/mdn/kuma-deployer.git
git clone https://github.com/mdn/mdn-storybook.git
git clone https://github.com/mdn/stumptown-deployer.git
git clone https://github.com/mdn/todo-vue.git
git clone https://github.com/mdn/todo-react.git
git clone https://github.com/mdn/todo-react-build.git
git clone https://github.com/mdn/_test_content_dont_use.git
git clone https://github.com/mdn/content.git
git clone https://github.com/mdn/archived-content.git
git clone https://github.com/mdn/machine-translation-testing-content.git
git clone https://github.com/mdn/translated-content-rendered.git
git clone https://github.com/mdn/translated-content.git

curl "https://api.github.com/orgs/mdn/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone
