---
- name: Add kuberetes repo key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes apt repo
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release|lower }} main"
    state: present
    update_cache: yes

- name: Install kubectl
  apt:
    name: kubectl
    state: present
    update_cache: yes
    cache_valid_time: 600
