# Default values for kumascript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/mozmar/kumascript
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 9080
  internalPort: 9080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
