apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: redirector
  name: redirector
  namespace: redirector
spec:
  type: NodePort
  selector:
    app: redirector
  ports:
    - name: http
      port: 80
      targetPort: 80
