autoscalingGroups:
   - name:
     minSize:
     maxSize:

awsRegion:

image:
  repository: gcr.io/google_containers/cluster-autoscaler
  tag: v0.4.0
  pullPolicy: IfNotPresent

extraArgs: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

podAnnotations: {}
replicaCount: 3

resources:
   limits:
     cpu: 100m
     memory: 300Mi
   requests:
     cpu: 100m
     memory: 300Mi

service:
  annotations: {}
  clusterIP: ""

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 8085
  type: ClusterIP

skipNodes:
  withLocalStorage: false
  withSystemPods: false
