---
- name: Download remote_syslog2
  get_url:
    url: https://github.com/papertrail/remote_syslog2/releases/download/v{{ package_version }}/remote-syslog2_{{ package_version }}_amd64.deb
    dest: /tmp/remote-syslog2_{{ package_version }}_amd64.deb

- name: Install remote_syslog2
  apt:
    deb: /tmp/remote-syslog2_{{ package_version }}_amd64.deb
    state: present

- name: Configure papertrail
  template:
    src: 'log_files.yml.j2'
    dest: '/etc/log_files.yml'
    owner: root
    group: root
    mode: 0644

- name: Start service
  service:
    name: remote_syslog
    enabled: yes
    state: started
