kind: Namespace
apiVersion: v1
metadata:
  name: fluentd
  labels:
    name: fluentd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: fluentd
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: fluentd
spec:
  template:
    metadata:
      name: fluentd
      namespace: fluentd
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      hostNetwork: true
      containers:
      - name: mozfluentd
        image: quay.io/mozmar/fluentd:latest
        resources:
          limits:
            cpu: 100m
            memory: 768Mi
        env:
          - name: "SYSLOG_HOST"
            value: "{{ .Values.fluentd.syslog_host }}"
          - name: "SYSLOG_PORT"
            value: "{{ .Values.fluentd.syslog_port }}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
