# Needed for when dependabot makes PRs. Their branches are added here to the 'mdn' repo.
branches:
  only:
    - master

language: node_js
node_js: lts/*

cache:
  yarn: true
  directories:
    - client/node_modules
    - server/node_modules
    - ssr/node_modules
    - content/node_modules

# Because https://github.com/travis-ci/travis-ci/issues/9445
before_install:
  - npm install -g yarn
  - yarn --version

matrix:
  include:
    - name: linting
      cache: yarn
      script:
        - ./scripts/ci-lint.sh
    - name: client
      cache: yarn
      script:
        - ./scripts/ci-client.sh
    - name: end-to-end
      cache: yarn
      script:
        - set -x
        - ./scripts/ci-end-to-end.sh
    - name: lockfile-check
      install: skip
      script:
        - ./scripts/ci-yarn-lockfile-check.sh
